#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../../terraform"
INVENTORY_FILE="$SCRIPT_DIR/../inventory/hosts.ini"

# Monitoring server IP: not managed by Terraform, set manually
# Usage: MONITORING_IP=1.2.3.4 bash update_inventory.sh
MONITORING_IP="${MONITORING_IP:-REPLACE_WITH_MONITORING_IP}"

echo "Reading Terraform outputs from: ${TERRAFORM_DIR}"
cd "$TERRAFORM_DIR"

STAGING_IP=$(terraform output -raw staging_public_ip)
PRODUCTION_IP=$(terraform output -raw production_public_ip)
RDS_ENDPOINT=$(terraform output -raw rds_endpoint)

mkdir -p "$(dirname "$INVENTORY_FILE")"

echo "Generating inventory: ${INVENTORY_FILE}"

cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by update_inventory.sh — $(date)
# Do not edit manually; re-run this script after terraform apply.

[monitoring]
${MONITORING_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-capstone.pem

[staging]
${STAGING_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-capstone.pem

[production]
${PRODUCTION_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-capstone.pem

[app_servers:children]
staging
production

[all_servers:children]
monitoring
app_servers

[all_servers:vars]
rds_endpoint=${RDS_ENDPOINT}
EOF

echo "Done. Inventory written to ${INVENTORY_FILE}"
cat "$INVENTORY_FILE"
