#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../../terraform"
INVENTORY_FILE="$SCRIPT_DIR/../inventory/hosts.ini"

echo "Reading Terraform outputs from: ${TERRAFORM_DIR}"
cd "$TERRAFORM_DIR"

MONITORING_IP=$(terraform output -raw monitoring_public_ip)
MONITORING_PRIVATE_IP=$(terraform output -raw monitoring_private_ip)
STAGING_IP=$(terraform output -raw staging_public_ip)
STAGING_PRIVATE_IP=$(terraform output -raw staging_private_ip)
PRODUCTION_IP=$(terraform output -raw production_public_ip)
PRODUCTION_PRIVATE_IP=$(terraform output -raw production_private_ip)
RDS_ENDPOINT=$(terraform output -raw rds_endpoint)

mkdir -p "$(dirname "$INVENTORY_FILE")"

echo "Generating inventory: ${INVENTORY_FILE}"

cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by update_inventory.sh — $(date)
# Do not edit manually; re-run this script after terraform apply.

[monitoring]
${MONITORING_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-capstone.pem

[staging]
${STAGING_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-capstone.pem

[production]
${PRODUCTION_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-capstone.pem

[app_servers:children]
staging
production

[all_servers:children]
monitoring
app_servers

[all_servers:vars]
rds_endpoint=${RDS_ENDPOINT}
monitoring_ip=${MONITORING_IP}
monitoring_private_ip=${MONITORING_PRIVATE_IP}
staging_ip=${STAGING_IP}
staging_private_ip=${STAGING_PRIVATE_IP}
production_ip=${PRODUCTION_IP}
production_private_ip=${PRODUCTION_PRIVATE_IP}
EOF

echo "Done. Inventory written to ${INVENTORY_FILE}"
cat "$INVENTORY_FILE"
