global:
  resolve_timeout: 5m

templates: []

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'null'

  routes:
    - match:
        severity: critical
      receiver: 'null'
      repeat_interval: 5m

    - match:
        severity: warning
      receiver: 'null'

receivers:
  - name: 'null'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
